### ISSUE TITLE
Пройти курс на Stepik по Java

### ISSUE THREAD

**Issue by GabovYegor** [GabovYegor/Java_practice#4]
[ссылка на курс](https://stepik.org/course/187)

**Comment by GabovYegor** [comment]
[Дополнительный материал по основам Java](https://math.sgu.ru/sites/chairs/prinf/materials/java/lesson1.htm)
[Дополнительный материал 2](https://www.geeksforgeeks.org/java/)

**Comment by ghost** [comment]
Completed.

**Comment by GabovYegor** [comment]
[книжка от Ярослава](https://vk.com/doc135208984_509145788?hash=5fe32198d8f3b06ce9&dl=210739aa12f5b31452)
